# Generated by Django 4.0.4 on 2022-04-19 03:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaenr_login', '0002_alter_myuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='dob',
            field=models.DateField(default=datetime.date(2022, 4, 18)),
        ),
    ]
